name: automerge-dependabot

on:
  pull_request:
    branches: [ develop ]
  check_suite:
    types:
      - completed

jobs:
  automerge-dependabot:
    name: Merge dependabot
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
          MERGE_COMMIT_MESSAGE: pull-request-title
          MERGE_DELETE_BRANCH: true
          MERGE_METHOD: "rebase"
