name: automerge-dependabot

on:
  pull_request_target:
    branches: [ develop ]
  check_suite:
    types:
      - completed

jobs:
  automerge-dependabot:
    name: Merge dependabot
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.2"
        env:
          GITHUB_TOKEN: "${{ secrets.MERGE_DEPENDABOT_GITHUB_TOKEN }}"
