name: gh-pages
on:
  push:
    branches:
      - main
      - develop

jobs:
  setup-gh-pages-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - run: npm install
      - run: echo running on branch ${GITHUB_REF##*/}
      - run: npm run doc ${GITHUB_REF##*/}
      - run: npm run coverage ${GITHUB_REF##*/}
      - run: cat "gh-pages/${GITHUB_REF##*/}/coverage/lcov.info" | npx coveralls
  update-gh-pages:
    needs: setup-gh-pages-files
    runs-on: ubuntu-latest
    steps:
      - uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: gh-pages

