name: npm-audit-fix
on:
  schedule:
    - cron:  '00 9 * * *'

jobs:
  setup-gh-pages-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          ref: develop
      - run: npm install
      - run: npm audit fix
      - run: |
          if git diff-index --quiet HEAD --; \
          then echo "CHANGES=false" >> $GITHUB_ENV; \
          else echo "CHANGES=true" >> $GITHUB_ENV; \
          fi
      - uses: peter-evans/create-pull-request@v3
        if: ${{ env.CHANGES == 'true' }}
        with:
          title: 'npm audit fix'
          commit-message: 'npm audit fix'
          branch: 'npm/audit-fix'
          base: 'develop'
          delete-branch: true
          labels: 'dependencies,javascript'
          # repo scoped token is necessary to make the pull request trigger other actions
          # unfortunately this changes the pull request author to the repo owner
          token: ${{ secrets.URL_BUILDER_GITHUB_TOKEN }}
