name: npm-audit-fix
on:
  push:
    branches:
      - develop
      - 'feature/npm-audit-fix-action'

jobs:
  setup-gh-pages-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - run: npm install
      - run: npm audit fix
      - run: |
          if git diff-index --quiet HEAD --; \
          then echo "CHANGES=false" >> $GITHUB_ENV; \
          else echo "CHANGES=true" >> $GITHUB_ENV; \
          fi
      - uses: peter-evans/create-pull-request@v3
        if: ${{ env.CHANGES == 'true' }}
        with:
          title: 'npm audit fix'
          commit-message: 'npm audit fix'
          branch: 'feature/npm-audit-fix-action'
          delete-branch: true
          labels: 'dependencies,javascript'
