name: npm-audit-fix
on:
  push:
    branches:
      - develop
      - 'feature/npm-audit-fix-action'

jobs:
  setup-gh-pages-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - run: npm install
      - run: npm audit fix
      - uses: peter-evans/create-pull-request@v3
        with:
          title: 'npm audit fix'
          commit-message: 'npm audit fix'
          branch: npm/audit-fix
          delete-branch: true
          labels: 'dependencies,javascript'
