name: test-and-deploy
on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [windows, macos, ubuntu]
        node: ['10', '12', '14']
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol native
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run lint
      - run: npm test
  setup-deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
    steps:
      - run: npm run travis-deploy ${GITHUB_REF##*/}
      - run: cat "gh-pages/${GITHUB_REF##*/}/coverage/lcov.info" | npx coveralls
  gh-pages-update:
    needs: setup-deploy
    runs-on: ubuntu-latest
    uses: JamesIves/github-pages-deploy-action@4.1.3
    with:
      branch: gh-pages
      folder: gh-pages
  gh-release:
    needs: setup-deploy
    runs-on: ubuntu-latest
    uses: softprops/action-gh-release@v1
    if: startsWith(github.ref, 'refs/tags/')
    env:
      GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
